# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

# Include remote taskfile (templates)
includes:

  k3d: https://raw.githubusercontent.com/defenseunicorns/JosueAvena/main/.taskfiles/k3d-terraform.yaml
  zarf: https://raw.githubusercontent.com/defenseunicorns/JosueAvena/main/.taskfiles/zarf-templates.yaml


vars:
  PROJECT: retro
  VERSION: 1.0.0
  ARCHITECTURE: amd64
  ZARF_DIR: ./retro

  REPOSITORY: ghcr.io/defenseunicorns/dashdays/josueavena/dosgames
  # PUBLISH_FLAGS: --insecure
  # DEPLOY_FLAGS: --insecure


tasks:
  default:
    cmds:
      - echo "Default command is a dummy command to allow downloading the remote templates by piping yes into the confirmation until it is updated to honor --yes"
  k3d-full: 
    cmds:
     - task: k3d-up
     - task: oci-deploy
     - task: oci-remove
     - task: k3d-down
  k3d-up: 
    cmds:
     - task: k3d:create
  k3d-down: 
    cmds:
     - task: k3d:destroy
  oci-deploy:
    cmds:
      - task: zarf:oci-deploy
      - task: zarf:service-health
        vars: { SERVICE: 'game', NAMESPACE: 'dos-games' }
  oci-remove:
    cmds: 
      - task: zarf:remove-oci