name: Deploy Environment
on:
  push:
    # branches:
    #   - main

env:
  DIR1: 'environments/uds-ci-commercial/bootstrap'
  DIR2: 'environments/uds-ci-commercial/deploy'
  uds-ci-ephemeral: 'environments/uds-ci-ephemeral'
permissions:
    id-token: write
    contents: read

defaults:
  run:
    # We need -e -o pipefail for consistency with GitHub Actions' default behavior
    shell: bash -e -o pipefail {0}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME }}
        role-session-name: ${{ github.job || github.event.client_payload.pull_request.head.sha || github.sha }}
        aws-region: us-west-2
        # 21600 seconds == 6 hours
        role-duration-seconds: 21600
    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: 3.30.1
    - name: Run Taskfile
      run: |
        export TASK_X_REMOTE_TASKFILES=1
        printf '%s\n' y n | task -y
        #yes | task -y
